# https://www.vd-developer.online/blog/vite-react-deploy-github
name: Deploy

on:
  push:
    branches:
      - github-pages

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env: 
          VITE_EMAIL: ${{ secrets.VITE_EMAIL }}
          VITE_TEL: ${{ secrets.VITE_TEL }}
          VITE_LOCATION: ${{ secrets.VITE_LOCATION }}
          VITE_GITHUB: ${{ secrets.VITE_GITHUB }}
          VITE_MAILJS_SERVICE_ID: ${{ secrets.VITE_MAILJS_SERVICE_ID }}
          VITE_MAILJS_TEMPLATE_ID: ${{ secrets.VITE_MAILJS_TEMPLATE_ID }}
          VITE_MAILJS_TEMPLATE_PUBLIC_KEY: ${{ secrets.VITE_MAILJS_TEMPLATE_PUBLIC_KEY }}
          VITE_LINK_TO_RESUME: ${{ secrets.VITE_LINK_TO_RESUME }}
          VITE_FULL_NAME: ${{ secrets.VITE_FULL_NAME }}
          VITE_LINKEDIN: ${{ secrets.VITE_LINKEDIN }}

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist 